config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  root "pages#home"
  get '/pages/home', to: 'pages#home'
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef <ApplicationRecord
  validates :chefname, presence:true , length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email ,presence:true ,length: {maximum: 500},
            format:{with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }, allow_nil: true
  before_save { self.email = email.downcase }
  has_many :recipes
end

app/models/recipe.rb
class Recipe <ApplicationRecord
  validates :name, presence:true
  validates :description ,presence: true , length:{minimum: 5 ,maximum: 5000}
  belongs_to :chef
  validates :chef_id ,presence:true
  default_scope -> { order(updated_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController <ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_chef, :logged_in?

  def current_chef
    @current_chef ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
    !!current_chef
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
before_action :set_chef, only: [:show, :edit, :update, :destroy]
before_action :require_same_user, only: [:edit, :update, :destroy]
before_action :require_admin, only: [:destroy]
  def index
    @chefs = Chef.all
    @chefs = Chef.paginate(page: params[:page], per_page: 5)
  end

  def new
    @chef = Chef.new
  end

  def show
    @chef = Chef.find(params[:id])
  end

  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      session[:chef_id] = @chef.id
      flash[:success] = "Welcome #{@chef.chefname} to MyRecipes App!"
      redirect_to chef_path(@chef)
    else
      render 'new'
    end
  end

  def edit
    @chef = Chef.find(params[:id])
  end

  def update
    @chef = Chef.find(params[:id])
    if @chef.update(chef_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to @chef
    else
      render 'edit'
    end
  end

def destroy
  if !@chef.admin?
    @chef.destroy
    flash[:danger] = "Chef and all associated recipes have been deleted"
    redirect_to users_path
  end
end

  private

  def set_chef
    @chef = Chef.find(params[:id])
  end

  def chef_params
    params.require(:chef).permit(:chefname, :email, :password, :password_confirmation)
  end

def require_same_user
  if current_chef != @chef and !current_chef.admin?
    flash[:danger] = "You can only edit or delete your own account"
    redirect_to chefs_path
  end
end

def require_admin
  if logged_in? & !current_chef.admin?
    flash[:danger] = "Only admin users can perform that action"
    redirect_to root_path
  end

end

end

app/controllers/pages_controller.rb
class PagesController <ApplicationController

  def home
    redirect_to recipes_path if logged_in?
  end


end

app/controllers/recipes_controller.rb
class RecipesController <ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def index
    @recipes= Recipe.all
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end

  def new
    @recipe = Recipe.new
  end

  def show
  end

  def create
      @recipe = Recipe.new(recipe_params)
      @recipe.chef = current_chef
      if @recipe.save
        flash[:success] = "Recipe was created successfully!"
        redirect_to recipe_path(@recipe)
      else
        render 'new'
      end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe deleted successfully"
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :description)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def require_same_user
    if current_chef != @recipe.chef and !current_chef.admin?
      flash[:danger] = "You can only edit or delete your own recipes"
      redirect_to recipes_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
  def new
    # will simply render the form
  end

  def create
    chef = Chef.find_by(email: params[:session][:email].downcase)
    if chef && chef.authenticate(params[:session][:password])
      session[:chef_id] = chef.id
      flash[:success] = "You have successfully logged in"
      redirect_to chef
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:chef_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@chef, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :chefname, "Choose Chefname" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :chefname, class: "form-control", placeholder: "Enter your name", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :email %>
        </div>
        <div class="col-md-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter your email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :password %>
        </div>
        <div class="col-md-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Choose a password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :password_confirmation, "Confirm Password" %>
        </div>
        <div class="col-md-8">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit "Create my account",class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: "Edit your profile" %>

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "showing all chefs" %>

<div align="center">
  <%= will_paginate %>
  <% @chefs.each do |chef| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">

          <li class="chef-title"><%= link_to chef.chefname.capitalize, chef_path(chef) %></li>
          <li><small><%= pluralize(chef.recipes.count, "recipe") if chef.recipes %>
          </small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Sign up for the application" %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: "Chef #{@chef.chefname}'s profile" %>
<div class="row">
  <!--<div class="col-md-4 col-md-offset-4 center">-->
    <!--<%#= gravatar_for @chef, size: 150 %>-->
  <!--</div>-->
</div>

<h4 align="center"><%= @chef.chefname %>'s recipes</h4>
<div align="center">
  <%= will_paginate @chef_recipes %>
</div>
<%= render 'recipes/recipe', obj: @chef_recipes %>
<div class="center">
  <%= will_paginate @chef_recipes %>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              prohibited this <%= obj.class %> from being saved:
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/layouts/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal",

                                    role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :name %>
          </div>
          <div class="col-md-8">
            <%= f.text_field :name, class: "form-control",

                             placeholder: "Name of recipe", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :description %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 10, class: "form-control",

                            placeholder: "Enter steps to create recipe" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
          </div>
        </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing",

                    recipes_path %> ]
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>">
          <a href="#" class="close" data-dismiss="alert">×</a>
          <%= msg %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
              aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Chefs", chefs_path %></li>
        <li><%= link_to "All Recipes", recipes_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
               role="button" aria-haspopup="true" aria-expanded="false">
              Recipes <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create a new recipe", new_recipe_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
               role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_chef.chefname.capitalize %>'s Profile <%= "Admin" if current_chef.admin? %>
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View your profile",
                              chef_path(current_chef) %></li>
              <li><%= link_to "Edit your profile",
                              edit_chef_path(current_chef) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", logout_path,
                              method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Reciepe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render'layouts/navigation'%>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to Recipes Application!</h1>

  <p><%= link_to "Sign up for the app", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %></p>
  <p><%= link_to "View all Recipes", recipes_path, class: "btn btn-danger btn-lg btn-xlarge" %></p>
</div>


<div class="row">
  <div class="col-lg-4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
  </div>
  <div class="col-lg-4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
  </div>
  <div class="col-lg-4">
    <h2>Heading</h2>
    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
    <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create recipe" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.description, length: 150) %></p>
      <p>
        <span class="quiet"><small>Created
          <%= time_ago_in_words(recipe.created_at) %> ago</small></span>
      </p>
      <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
        <div class="recipe-actions">
          <%= link_to "Edit this recipe",
                      edit_recipe_path(recipe),
                      class: "btn btn-xs btn-warning" %>
          <%= link_to "Delete this recipe", recipe_path(recipe),
                      method: :delete,
                      data: { confirm: "Are you sure you want to delete this recipe?" },
                      class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "edit an existing recipe" %>
<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "showing all recipes" %>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'recipe', obj: @recipes %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "create a new recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>
<div class="well col-md-8 col-md-offset-2">
  <h4 class="center description"><strong>Description: </strong></h4>
  <hr />
  <%= @recipe.description %>
  <hr />
  <div class="pull-right">
    <p class="center">
      Created by:
    </p>
    <p>
      <small><%= @recipe.chef.chefname %></small>
    <div class="pull-right">
      <%= time_ago_in_words(@recipe.created_at) %> ago
    </div>
    </p>
  </div>
  <div class="recipe-actions">
      <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
           <%= link_to "Edit this recipe", edit_recipe_path(@recipe),
                  class: "btn btn-xs btn-warning" %>
      <%= link_to "Delete this recipe", recipe_path(@recipe),
                  method: :delete,
                  data: { confirm: "Are you sure you want to delete this recipe?" },
                  class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "Return to recipes listing", recipes_path,
                class: "btn btn-xs btn-primary" %>

  </div>
  </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this <%= obj.class %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.capitalize %></h1>
<hr />